Combinacion ejercicios base datos
2DAW-CarlosIII/marcapersonalFP23_24 pull request #190
Opened 2023-12-04 07:56 UTC by PatricioTristante

Todos los ejercicios de mi grupo mezclados

2023-12-04 14:23 UTC, mxrqxxz reviewed
En la vista de users.edit el campo nombre se queda en strong, queda un poco feo.

Si no me equivoco no se han resuelto los siguientes issues:

 Uso de la base de datos: Docentes #134 
 Uso de la base de datos: Estudiantes #133

2023-12-04 14:23 UTC, mxrqxxz commented on app/Http/Controllers/ActividadController.php
> +        $actividadSeleccionada = DB::table('actividades')->findOr($id);
Ese 'findOr' creo que está incompleto. (ese y todos)

2023-12-04 15:35 UTC, Angel212000 requested changes
-Las issues de Docentes y Estudiantes no están resueltas

-No pasa la mayoría de los test

![image](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/assets/148429717/bf6fac6b-deb1-4717-aa43-549ca9876dec)

-La seccion actividades parece que no recoge de la base de datos

![image](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/assets/148429717/1ed8d80e-b0c4-4d0d-9d7f-45ee50a4b3f9)

-El edit y el show muestra lo siguiente

![image](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/assets/148429717/a8deabb3-ea75-40e7-a447-515469fc7f76)

![image](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/assets/148429717/f7842b69-aed2-4ca0-9d83-b18011263186)

Creo que todo ello se debe a errores en el findOrFail, porque se han escrito como findOr

2023-12-04 19:20 UTC, alexcgar commented
![image](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/assets/148429351/0a572e13-f986-4fe6-b143-03e9379b5c16)
recordar que tenéis que arreglar el rand

2023-12-05 07:02 UTC, alexcgar requested changes
Tenéis que arreglar los comentarios mencionados

2023-12-05 07:35 UTC, closed without merging