Issue en proceso
2DAW-CarlosIII/marcapersonalFP23_24 pull request #316
Opened 2023-12-16 23:19 UTC by ArturoGGP

A FALTA DE SOLUCIONAR UN FALLO

En el caso de que el docente_validador sea null, en la página aparece Error 404 en vez de aparecer el show con el botón, no sé muy bien que puede estar dando error. Lo subo por si alguien quiere echarle un vistazo a ver si se le ocurre que puede ser. Sigo trabajando en él de todos modos

Issue #297

2023-12-17 16:42 UTC, avcluis commented on resources/views/reconocimientos/index.blade.php
>                  <h3>Estudiante {{ $reconocimiento->estudiante_id }}</h3>
El Issue dice, que en el index de reconocimientos, solamente debe aparecer:
-nombre de la actividad
-nombre del estudiante.
Debes eliminar los demas campos innecesarios; como estudiante_id

2023-12-17 17:02 UTC, avcluis commented on resources/views/reconocimientos/index.blade.php
>                  <h3>Estudiante {{ $reconocimiento->estudiante_id }}</h3>
El Issue dice, que en el index de reconocimientos, solamente debe aparecer:
-nombre de la actividad
-nombre del estudiante.
Debes eliminar los demas campos innecesarios; como estudiante_id

2023-12-17 17:02 UTC, avcluis commented on resources/views/reconocimientos/index.blade.php
>                  <a href="{{ $reconocimiento->documento }}">
No se debe ver el documento en index. Eliminalo

2023-12-17 17:02 UTC, avcluis commented on resources/views/reconocimientos/show.blade.php
En esta vista, también muestras datos innecesarios. Eliminalos.

2023-12-17 17:05 UTC, avcluis requested changes
Hay varias cosas que debes modificar. Y solucionar el funcionamiento del validador.

2023-12-17 17:05 UTC, avcluis commented on app/Http/Controllers/ReconocimientoController.php
> +    public function putValidate(Request $request, $id)
Cuando en la vista reconocimientos show, intentas acceder al reconocimiento cuyo docente_validador es null, se debería mostrar el botoón de validar.
Sin embargo, se lanza un error 404.
El error es debido a esta función. Revisala

2023-12-17 17:05 UTC, avcluis commented on app/Http/Controllers/ReconocimientoController.php
> +        $reconocimiento->docente_validador = $request->input('validador');
No entiendo muy bien el funcionamiento de : $request->input('validador');

2023-12-18 00:26 UTC, avcluis commented on routes/web.php
> +    Route::get('/show/{id}', [ReconocimientoController::class, 'getShow'])->where('id', '[0-9]+')->middleware('auth');
No protejas la vista show

2023-12-18 00:28 UTC, avcluis commented on resources/views/reconocimientos/show.blade.php
> +                    Validado por {{ $user -> nombre }} {{ $user -> apellidos }}
Estas mostrando el nombre y apellidos de un usuario. Debes trabajar con la tabla docentes.

2023-12-18 18:48 UTC, raulIzquierdoPujante reviewed
Funcionando correctamente, a falta de eliminar algunos fragmentos de código que muestran datos que no deben aparecer en las vistas

2023-12-18 18:48 UTC, raulIzquierdoPujante commented on resources/views/reconocimientos/show.blade.php
No es necesario mostrar el ID de estudiante, tampoco el ID de actividad

2023-12-18 18:48 UTC, raulIzquierdoPujante commented on resources/views/reconocimientos/index.blade.php
>                  <a href="{{ $reconocimiento->documento }}">
Elimina el documento del index

2023-12-19 10:56 UTC, closed without merging