x-Total de la cabecera filtrado #458 jonatan
2DAW-CarlosIII/marcapersonalFP23_24 pull request #469
Opened 2024-01-21 15:19 UTC by JonatanMolina91

#458

2024-01-22 16:29 UTC, Angel212000 reviewed
Funciona perfectamente

2024-01-22 19:04 UTC, ArturoGGP approved these changes
Funciona correctamente

2024-01-22 23:11 UTC, Manuelfsr requested changes
Revisa los comentarios.

2024-01-23 07:31 UTC, JonatanMolina91 commented on package.json
Lo se, pero no fue modificación mía, el problema esta que cuando use el composer y el nmp install en casa me lo modifico de esa manera, si as visto el archivo es solo que usa una versión mas reciente de las dependencias y el orden el cual se llaman

2024-01-23 08:22 UTC, closed without merging