CuentaRegistrosDespuesFiltro
2DAW-CarlosIII/marcapersonalFP23_24 pull request #473
Opened 2024-01-21 16:54 UTC by Angel212000

#458

2024-01-22 19:08 UTC, ArturoGGP approved these changes
Funciona correctamente

2024-01-22 23:14 UTC, Manuelfsr commented on app/Http/Middleware/ReactAdminResponse.php
> -            $response->header('X-Total-Count',$modelClassName::count());
Bien cambiado el nombre de la variable, pero te falta la comprobación de si existe countRegister en la request.

2024-01-22 23:15 UTC, Manuelfsr requested changes
Revisa el comentario.

2024-01-23 07:49 UTC, JonatanMolina91 commented on app/Http/Middleware/ReactAdminResponse.php
> +            if($countRegister) {
Bien este if, pero teneis el   abort_unless(property_exists($request->route()->controller, 'modelclass'), 500, "It must exists a modelclass property in the controller."); para controlar la variable vacio, pero desde mi punto de vista a si vale.

2024-01-23 07:49 UTC, JonatanMolina91 approved these changes

2024-01-23 08:22 UTC, closed without merging