Cabecera X-Total-Count adaptada a filters Arturo
2DAW-CarlosIII/marcapersonalFP23_24 pull request #475
Opened 2024-01-21 17:23 UTC by ArturoGGP

#458

2024-01-22 16:35 UTC, Angel212000 reviewed
Funciona perfectamente

2024-01-22 23:04 UTC, Manuelfsr commented on app/Http/Middleware/ReactAdminResponse.php
> +            $modelClassName = $request->route()->controller->totalResultados;
Funciona pero el nombre de la variable modelClassName no tiene sentido ahí... Además, el control precio de para el código con el abort_unless si no existe la propiedad modelclass tienes que modificarlo para comprobar si totalResultados existe.

2024-01-22 23:05 UTC, Manuelfsr requested changes
Revisa el comentario que he dejado.

2024-01-23 07:34 UTC, ArturoGGP commented
Muchas gracias Manu :DD

2024-01-23 07:56 UTC, JonatanMolina91 approved these changes
Se puede hacer mas optimo el código, hay varias variables que sobran, pero vamos tampoco va a  gastar mucha memoria, por mi funciona bien y vale.

2024-01-23 08:22 UTC, closed without merging