Issue seeder participantes proyectos
2DAW-CarlosIII/marcapersonalFP23_24 pull request #566
Opened 2024-01-25 09:08 UTC by pytocino

#562

2024-01-27 10:43 UTC, Manuelfsr commented on database/seeders/ParticipantesProyectosTableSeeder.php
> +            $user->proyectos()->attach($proyectos->random(rand(0, 2))->pluck('id'));
Una manera muy limpia de hacerlo, me la apunto.

2024-01-27 10:44 UTC, Manuelfsr commented
El issue está resuelto, pero has añadido cambios que no corresponden a este ejercicio, revisa eso.

2024-01-27 10:44 UTC, Manuelfsr requested changes
Revisa el comentario.

2024-01-29 07:05 UTC, closed without merging

2024-01-29 07:10 UTC, Zaidanxp reviewed
Has añadido cambios que no pertenecen al issue que has resuelto