Seeder y tabla de participantes_proyectos
2DAW-CarlosIII/marcapersonalFP23_24 pull request #587
Opened 2024-01-27 17:14 UTC by Zaidanxp

#562

2024-01-27 17:59 UTC, Manuelfsr commented on database/seeders/ParticipantesProyectosTableSeeder.php
> +            for($iterator = 0; $iterator < $userProyects; $iterator++){
Hay otro error que no has controlado. ¿Qué pasa si salen dos ids de proyectos iguales para el mismo usuario? Que da error por clave duplicada. Debes controlar que, si se le asigna dos proyectos al mismo usuario, no sea el mismo proyecto duplicado.

2024-01-27 17:59 UTC, Manuelfsr requested changes
Revisa el comentario.

2024-01-27 19:18 UTC, Zaidanxp commented on database/seeders/ParticipantesProyectosTableSeeder.php
> +            for($iterator = 0; $iterator < $userProyects; $iterator++){
Corregido

2024-01-29 11:13 UTC, albsierra commented
Para que se repartiera correctamente el esfuerzo, indiqué que cada uno modificara el seeder que le había tocado en el issue anterior. En tu caso, el [issue participantes_proyectos](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/issues/513) le tocó a otros compañeros.

2024-01-29 11:13 UTC, closed without merging