Seed users competencias Jonatan
2DAW-CarlosIII/marcapersonalFP23_24 pull request #590
Opened 2024-01-27 18:41 UTC by JonatanMolina91

#568

2024-01-27 19:55 UTC, DonHonorio commented on database/factories/UserCompetenciaFactory.php
>          return [
No lo has entendido, dice `El número de registros relacionados serán 0, 1 o 2.` Se refiere al número de registros que se añaden de una tabla a cada instancia de la otra, por ejemplo, añadir 0,1 o 2 registros de competencia a cada usuario. (Que es lo que hemos hecho Jesús y yo)

2024-01-27 19:57 UTC, DonHonorio requested changes
Dice `vamos a modificar los seed existentes de las tablas intermedias.`. En este caso no hay que usar factory.

2024-01-28 15:42 UTC, JonatanMolina91 commented
Cambios realizados

2024-01-28 17:29 UTC, DonHonorio approved these changes
Ahora no puedo objetar a aprovar este pull request

2024-01-28 19:42 UTC, mdmmr97 requested changes

2024-01-28 19:42 UTC, mdmmr97 commented on database/seeders/UsersCompetenciasTableSeeder.php
> +                $usuario->competencias()->attach($competencia->id);
Cuando vas a introducirle una nueva competencia al usuario y ya había una introducida con anterioridad deberías comprobar que la nueva no es la misma que la anterior para que no haya errores

2024-01-29 07:10 UTC, mdmmr97 approved these changes

2024-01-29 07:12 UTC, mdmmr97 commented on database/seeders/UsersCompetenciasTableSeeder.php
> +                $usuario->competencias()->attach($competencia->id);
Como ha dicho que lo del duplicado no importa te lo apruebo

2024-01-29 11:07 UTC, albsierra commented
Para que se repartiera correctamente el esfuerzo, indiqué que cada uno modificara el seeder que le había tocado en el issue anterior. En tu caso, el [issue users_competencias ](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/issues/526) le tocó a otros compañeros.

2024-01-29 11:07 UTC, closed without merging