issue completado
2DAW-CarlosIII/marcapersonalFP23_24 pull request #595
Opened 2024-01-28 10:08 UTC by raulIzquierdoPujante

He añadido control de duplicados para las competencias

2024-01-29 22:30 UTC, ArturoGGP requested changes

2024-01-29 22:30 UTC, ArturoGGP commented on database/seeders/UsersCompetenciasTableSeeder.php
> +                    do {
Al utilizar un do-while, primero se ejecuta el código del do y luego se hace la comprobación del while, y hace que algunas veces se añadan 3 competencias a un mismo usuario.

![imagen](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/assets/149622808/6ead8952-0029-404b-8e24-a00fe84f8284)

2024-01-29 22:30 UTC, ArturoGGP commented on database/seeders/UsersCompetenciasTableSeeder.php
> +                    do {
con un simple while en vez de do-while se solucionaría

2024-01-30 07:32 UTC, raulIzquierdoPujante commented on database/seeders/UsersCompetenciasTableSeeder.php
> +                    do {
Gracias por la aclaración compañero, lo he corregido en el último commit

2024-01-30 10:25 UTC, Manuelfsr approved these changes

2024-01-30 11:11 UTC, ArturoGGP approved these changes

2024-01-30 17:59 UTC, merged