Cambiado la visualizacion de la tabla idioma de react admin
2DAW-CarlosIII/marcapersonalFP23_24 pull request #597
Opened 2024-01-28 16:11 UTC by JonatanMolina91

Lo he hecho rápido, si hay algun fallo intentare corregirlo antes del lunes

2024-01-29 07:05 UTC, Manuelfsr requested changes
Todo se muestra correctamente, pero yo no mostraría todos los datos en el index, dejaría algunos para mostrarlos en el show.

2024-01-29 07:09 UTC, JonatanMolina91 commented
Dime que campos quieres que se muestre en el index, jefe y realizo los cambios

2024-01-29 18:01 UTC, mdmmr97 commented on resources/js/react-admin/Pages/Idiomas.jsx
>  const NombreInput = () => (
Este campo lo quitaría porque no filtra

2024-01-29 18:10 UTC, mdmmr97 requested changes

2024-01-29 18:10 UTC, mdmmr97 commented on resources/js/react-admin/Pages/Idiomas.jsx
>              <NombreInput />
Simplemente pondría directamente el <TextInput source="english_name" />

2024-01-29 18:10 UTC, mdmmr97 commented on resources/js/react-admin/Pages/Idiomas.jsx
> +          <TextField source="alpha2" />
Creo que quitaría los alpha3

2024-01-29 18:10 UTC, mdmmr97 commented on app/Http/Controllers/API/IdiomaController.php
> +        $campo = ['english_name'];
Pondría que también tenga en cuenta el nombre nativo

2024-01-29 21:31 UTC, mdmmr97 approved these changes

2024-01-30 06:59 UTC, Manuelfsr approved these changes

2024-01-30 18:01 UTC, merged