seeder Usuario-Competencias
2DAW-CarlosIII/marcapersonalFP23_24 pull request #599
Opened 2024-01-28 18:30 UTC by alexcgar

#559

2024-01-28 20:00 UTC, mdmmr97 requested changes

2024-01-28 20:00 UTC, mdmmr97 commented on database/seeders/UsersCompetenciasTableSeeder.php
>          UserCompetencia::factory(5)->create();
El factory lo tienes que quitar porque lo que estamos haciendo en la practica es para sustituirlo

2024-01-28 20:00 UTC, mdmmr97 commented on database/seeders/UsersCompetenciasTableSeeder.php
> +                $usuario->competencias()->attach($competencia->id);
Antes de asignarle una nueva competencia al usuario deberías comprobar que si tiene una competencia asignada de antes no sea la misma que la nueva

2024-01-29 07:25 UTC, alexcgar commented on database/seeders/UsersCompetenciasTableSeeder.php
> +                $usuario->competencias()->attach($competencia->id);
Gracias!

2024-01-29 11:08 UTC, albsierra commented
Para que se repartiera correctamente el esfuerzo, indiqué que cada uno modificara el seeder que le había tocado en el issue anterior. En tu caso, el [issue users_competencias ](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/issues/526) le tocó a otros compañeros.

2024-01-29 11:08 UTC, closed without merging