autorización Proyecto
2DAW-CarlosIII/marcapersonalFP23_24 pull request #625
Opened 2024-02-02 07:31 UTC by DonHonorio

#614

2024-02-03 09:53 UTC, raulIzquierdoPujante approved these changes
Funciona correctamente, no he encontrado ningún error.

@albsierra sin embargo estoy viendo que ocurre lo siguiente cuando se intenta eliminar un proyecto (logueado con el docente propietario del mismo) 

![2024-02-03 10_42_19-Window](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/assets/148429766/43aa843b-6994-4268-93fe-ad12fe497596)

2024-02-03 17:28 UTC, DonHonorio commented
> sin embargo estoy viendo que ocurre lo siguiente cuando se intenta eliminar un proyecto (logueado con el docente propietario del mismo)

Es normal ya que intentas borrar un registro que está como FK en otra tabla y te lo impide, pero eso luego lo solucionaremos.

2024-02-03 23:20 UTC, avcluis commented on app/Policies/ProyectoPolicy.php
> +    public function viewAny(User $user): bool
Debes modificar esta función, para que los usuarios anónimos puedan acceder.

2024-02-03 23:20 UTC, avcluis commented on app/Policies/ProyectoPolicy.php
> +    public function view(User $user, Proyecto $proyecto): bool
Debes modificar esta función, para que los usuarios anónimos puedan acceder.

2024-02-03 23:22 UTC, avcluis requested changes
No se puede acceder a las vistas show/index con usuario anónimo. Te he indicado las funciones que debes modificar para permitirlo. 
Todo lo demás funciona perfectamente.

2024-02-04 11:11 UTC, DonHonorio commented on app/Policies/ProyectoPolicy.php
> +    public function viewAny(User $user): bool
Tienes razón: si no pones opcional el parámetro User, impide entrar a los anónimos, ya lo he solucionado, dame ese check verde ;-)

2024-02-04 12:30 UTC, avcluis approved these changes
Todo correcto!!!

2024-02-05 08:37 UTC, closed without merging