Issue Ejercicios autorización Familias Profesionales Idiomas
2DAW-CarlosIII/marcapersonalFP23_24 pull request #634
Opened 2024-02-02 18:21 UTC by MarianoConesa

#613

2024-02-02 18:54 UTC, ArturoGGP commented
Perdón, que me he equivocado con el numero del (#)

2024-02-03 08:13 UTC, albsierra commented
Hay ficheros que no deberían haberse incorporado al pull request

2024-02-04 12:04 UTC, CarlosLlangostera requested changes
Faltaría añadir el método authorize en las acciones en las que se debe comprobar que el usuario tiene permisos para poder realizarlas. Es decir, habría que añadirlo tanto en FamiliaProfesionalController como en IdiomaController, en los métodos store, update y destroy. [Aquí](https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/blob/master/documentos/0613_Servidor/102_policies.md#a-trav%C3%A9s-de-controller-helpers) lo explica.

Los ficheros app/Http/Middleware/EnsureEmailIsVerified.php y resources/views/.gitkeep no serían necesarios en el pull request.

Esto no está mal pero en las Policies hay redundancia devolviendo "$user->esAdmin()" en los métodos create, update, delete, restore y forceDelete, puesto que el método before ya autoriza a los administradores a realizar cualquier acción. Por ello, se podría devolver simplemente "false".

Faltaría añadir el símbolo "?" delante de User en los métodos view y viewAny para indicar que se trata de un parámetro opcional, ya que estas acciones también pueden ser realizadas por usuarios anónimos.

Por lo demás creo que está todo bien

2024-02-04 13:32 UTC, ArturoGGP requested changes
También añadir los cambios extra a otros archivos, que no son necesarios

2024-02-04 13:32 UTC, ArturoGGP commented on app/Policies/FamiliaProfesionalPolicy.php
> +    public function viewAny(User $user): bool
Como no es necesario tener un usuario registrado, habrá que cambiar User $user por ?User $user.

Referencia: #631

2024-02-04 13:32 UTC, ArturoGGP commented on app/Policies/FamiliaProfesionalPolicy.php
> +    public function view(User $user, FamiliaProfesional $familiaProfesional): bool
Realizar los mismos cambios comentados anteriormente

2024-02-04 13:32 UTC, ArturoGGP commented on app/Policies/IdiomaPolicy.php
> +    public function viewAny(User $user): bool
Realizar los mismo cambios que en FamiliaProfesionalPolicy

2024-02-04 13:32 UTC, ArturoGGP commented on app/Http/Controllers/API/FamiliaProfesionalController.php
> +    /**
Necesarias las funciones authorize en store, update y delete. (Via Helpers)

2024-02-04 13:32 UTC, ArturoGGP commented on app/Http/Controllers/API/IdiomaController.php
> +    /**
Necesarias las funciones authorize en store, update y delete. (Via Helpers)

2024-02-04 15:14 UTC, CarlosLlangostera approved these changes
No son necesarios los ficheros app/Http/Middleware/EnsureEmailIsVerified.php y resources/views/.gitkeep pero por lo demás creo que ya está todo bien

2024-02-05 08:37 UTC, closed without merging