Solucionado retraso frente a upstream + correción función delete
2DAW-CarlosIII/marcapersonalFP23_24 pull request #638
Opened 2024-02-03 09:21 UTC by raulIzquierdoPujante

#614

2024-02-03 23:35 UTC, avcluis commented on app/Policies/ProyectoPolicy.php
> +    public function before(User $user, $ability)
Para que los usuarios anónimos tengan acceso, hay que añadir ? delante de User.

2024-02-03 23:36 UTC, avcluis commented on app/Policies/ProyectoPolicy.php
> +    public function viewAny(User $user): bool
Lo mismo aquí. Añade también la interrogación.

2024-02-03 23:40 UTC, avcluis commented on app/Policies/ProyectoPolicy.php
> +    public function viewAny(User $user): bool
Para que los usuarios anónimos tengan acceso,  añade "?" delante de User.

2024-02-03 23:40 UTC, avcluis commented on app/Policies/ProyectoPolicy.php
> +    public function view(User $user, Proyecto $proyecto): bool
Lo mismo aquí.

2024-02-03 23:41 UTC, avcluis requested changes
No he podido comprobarlo en mi máquina, debido a que me da un error de merge. No me ha pasado revisando los pull de los demás compañeros pero es posible que sea mi máquina (no lose). Aún así he revisado tu código y todo parece estar correcto, excepto los usuarios anónimos, te he indicado como arreglarlo, simplemente añade "?" y estaría todo perfecto.

2024-02-04 11:20 UTC, DonHonorio commented on app/Policies/ProyectoPolicy.php
> +    public function viewAny(User $user): bool
@raulIzquierdoPujante Porque si haces una peticion a la api desde incognito, no te deja acceder ya que los usuarios anónimos no se autentican:
![image](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/assets/121085541/0582854f-1d31-4af8-bcdb-66cdb94d1e00)

2024-02-04 11:28 UTC, DonHonorio requested changes
A diferencia de Luis, a mí me funciona bien tu pull request y lo único q hay que cambiar es permitir la entrada a la api de los usuarios anónimos como bien a dicho Luis antes.
Tienes que poder hacer una petición en incógnito a proyectos como esta:
![image](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/assets/121085541/43614323-6f0d-440e-930c-c47cec35dc24)

2024-02-04 13:35 UTC, raulIzquierdoPujante commented
Gracias por las aclaraciones, realizado nuevo pull con las correcciones

2024-02-04 14:09 UTC, DonHonorio approved these changes
Ahora si está todo correcto.

2024-02-04 14:26 UTC, avcluis approved these changes

2024-02-05 08:37 UTC, closed without merging