Issue avatar (no consigo que funcione correctamente)
2DAW-CarlosIII/marcapersonalFP23_24 pull request #680
Opened 2024-02-07 19:42 UTC by avcluis

#667
Al hacer el update con la imagen, me da un error "Array to string conversion"
![image](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/assets/134608918/dd80fa59-3783-47b7-85c3-f4ad5aa5d8e6)
Pero en la base de datos me almacena lo siguiente:
![image](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/assets/134608918/e0f502c5-713d-425c-85e7-1b0d97ac2089)
{"rawFile":{"path":"descarga.jpeg"},"src":"blob:http:\/\/marcapersonalfp.test\/ef6bd0e6-e40e-400c-9eb5-d092b92bc9dc","title":"descarga.jpeg"}

No consigo cambiarlo. Si alguien le puede echar un vistazo a ver si ve algo raro se agradece.

2024-02-07 20:21 UTC, mxrqxxz requested changes
Tu problema creo que viene principalmente del dataProvider, el condicional de params.data.attachments, prueba con los cambios que te he dicho

2024-02-07 20:21 UTC, mxrqxxz commented on resources/js/react-admin/dataProvider.ts
> +    formData.append('avatar', params.data.avatar.rawFile)
formData.append('avatar', params.data.attachments.rawFile)

2024-02-07 20:21 UTC, mxrqxxz commented on app/Http/Resources/UserResource.php
> +            'avatar' => $this->avatar
'attachments' => $this->avatar

2024-02-07 20:21 UTC, mxrqxxz commented on resources/js/react-admin/Pages/Users.jsx
> +            <ImageInput source="avatar" label="Avatar" style={{ border: '2px dashed #ccc', padding: '10px', maxWidth: '180px' }}>
<ImageInput source="attachments" label="Avatar" style={{ border: '2px dashed #ccc', padding: '10px', maxWidth: '180px' }}>

2024-02-07 20:21 UTC, mxrqxxz commented on resources/js/react-admin/Pages/Users.jsx
> +            <ImageInput source="avatar" label="Avatar" style={{ border: '2px dashed #ccc', padding: '10px', maxWidth: '180px' }}>
En userShow cambia de imageField el source, que se quede asi
<ImageField source="attachments.src" title="name" label="Foto de perfil" />

2024-02-07 20:57 UTC, mxrqxxz commented on resources/js/react-admin/Pages/Users.jsx
> +            <ImageInput source="avatar" label="Avatar" style={{ border: '2px dashed #ccc', padding: '10px', maxWidth: '180px' }}>
ImageField source="attachments.src" title="name" label="Foto de perfil"

2024-02-07 21:13 UTC, avcluis commented
Ya funciona como es debido.

2024-02-08 08:26 UTC, mxrqxxz requested changes
Habría que refactorizar el dataProvider para que en un futuro si metemos más archivos incluso con distinto nombre que no dé futuros errores, lo ideal sería dejar el update solo con un switch y todo lo demás que sean métodos en función del recurso que llame al método update

2024-02-09 18:32 UTC, closed without merging