Issue Avatar
2DAW-CarlosIII/marcapersonalFP23_24 pull request #687
Opened 2024-02-07 22:10 UTC by StackFlowOver

2024-02-07 22:10 UTC, StackFlowOver commented
#667

2024-02-08 07:43 UTC, JavierColmena commented on app/Http/Resources/UserResource.php
> +                'src' => asset('storage/' . $this->avatar),
No pasaría nada en principio, pero por si acaso dejarlo de la siguiente manera:
`'src' => asset('/storage/' . $this->avatar),`

2024-02-08 08:06 UTC, JavierColmena requested changes
Me equivocado en la corrección, disculpa.

2024-02-08 08:35 UTC, mxrqxxz commented on resources/js/react-admin/authProvider.ts
> +                data.json.avatar = 'http://acreditacion.educadgo.gob.mx/static/img/user.png'
Hay que coger la foto que tenga el usuario, no esa, si te ha gustado puedes ponerla en el caso de que el usuario no tenga foto

2024-02-08 08:45 UTC, mrm95 requested changes
No te muestra la foto de perfil que vas a subir, ni se ve en el show ni se actualiza arriba a la izquierda

2024-02-09 18:32 UTC, closed without merging