Modificación del Proyecto para Trabajar con un Repositorio Común Arturo
2DAW-CarlosIII/marcapersonalFP23_24 pull request #713
Opened 2024-02-14 18:21 UTC by ArturoGGP

#694

2024-02-14 18:21 UTC, ArturoGGP commented
![imagen](https://github.com/2DAW-CarlosIII/marcapersonalFP23_24/assets/149622808/1bb17e80-d0e2-49a8-900b-dfc4ece40400)
Me ocurre ese error al borrar, no sé que puede ser

2024-02-15 07:57 UTC, Zaidanxp commented on app/Http/Controllers/API/ProyectoController.php
El objeto en la base de datos solo se actualizará si has modificado el campo de la carpeta del proyecto. Por ejemplo, si solo cambias la ``calificación``, la actualización no se llevará a cabo a menos que también hayas modificado el campo de la carpeta del proyecto.

2024-02-15 08:06 UTC, Zaidanxp requested changes
Si el usuario no sube el proyecto pero actualiza otro campo del formulario, ``dataProvider`` agregará el archivo del proyecto a la solicitud sin que el usuario lo haya insertado, lo que provoca el mensaje de error ``The dataProvider threw an error. It should return a rejected Promise instead.``. Por lo demás, está bien

2024-02-15 09:45 UTC, Angel212000 commented
Aparte de los errores comentados por el compañero no veo ninguno más. Con cambiar eso bastaría para que funcionase correctamente.

2024-02-15 09:47 UTC, Angel212000 requested changes
Realiza los cambios marcados por el compañero

2024-02-15 20:34 UTC, ArturoGGP commented on app/Http/Controllers/API/ProyectoController.php
Aun sacando el update fuera del if me aparece el error del dataProvider.
Subo los cambios igualmente

2024-02-15 20:41 UTC, ArturoGGP commented
@Angel212000 @Zaidanxp Si lo probáis de nuevo y me decís, lo agradecería muchísimo. Eso sí, cuando podáis, que ahora estamos todos con las tareas hasta el cuello y no quiero que esto suponga mucha carga extra. Muchas gracias a los dos.

2024-02-16 09:21 UTC, Zaidanxp commented on app/Http/Controllers/API/ProyectoController.php
Ahora si funciona, no hace falta que pongas el update dentro del bucle ya que ahí es donde te hará falta la ``url_github`` que le asignas al proyectoData. Por lo que tendrás que actualizar el objeto ``proyecto`` antes del bucle

2024-02-16 10:39 UTC, closed without merging